server:
  port: 8080
  undertow:
    threads:
      worker: 20
      io: 2

spring:
  application:
    name: butterfly-framework

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Netty RPC配置
netty:
  server:
    port: 8090
    boss-thread-count: 1
    worker-thread-count: 4
    tcp-backlog: 1024
    connect-timeout: 3000
    max-frame-length: 65535
  client:
    server-address: localhost
    server-port: 8090
    connect-timeout: 3000
    max-frame-length: 65535
    reconnect-interval: 5000
    ssl-enabled: false

rpc:
  interval: 5000
  timeout: 2000
  max-failures: 3
  retry:
    enabled: true
    max-retries: 3
    initial-delay-millis: 1000
    max-delay-millis: 5000
    multiplier: 2.0
  health-check:
    enabled: true
    interval-millis: 10000
    timeout-millis: 3000
    max-failure-count: 3